/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up with email + password + displayName */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 초이스 피드 (질문 + 랜덤 후보 4명)
         * @description questionId 없으면 새 질문(초기/스킵), 있으면 같은 질문 + 새 후보(다시 섞기).
         */
        get: operations["ChoiceController_getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/choices/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카드 선택 기록 후 다음 피드 반환
         * @description "나"(임시 유저)를 selector로 기록 → 받은픽 데이터의 출처.
         */
        post: operations["ChoiceController_select"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/viewer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 유저("나") 조회 (프리미엄 여부 포함) */
        get: operations["ViewerController_getViewer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/viewer/premium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 프리미엄 구독('가입하기') — 즉시 프리미엄 ON(임시) */
        post: operations["ViewerController_subscribePremium"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/received-picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 나를 픽한 사람 목록 + 각자의 받은픽 Top3
         * @description 비프리미엄이면 selector 사진은 서버에서 가려진다(photoUrl=null).
         */
        get: operations["ReceivedPicksController_getReceivedPicks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 소통 목록(메시지함) */
        get: operations["ConversationsController_getConversations"];
        put?: never;
        /** 소통하기 — 대화 생성(이미 있으면 반환) */
        post: operations["ConversationsController_createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 메시지 히스토리 (열면 읽음 처리) */
        get: operations["ConversationsController_getMessages"];
        put?: never;
        /** 메시지 전송 (REST 폴백; 정식 송신은 소켓) */
        post: operations["ConversationsController_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness check (app + DB) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example P@ssw0rd! */
            password: string;
            /** @example Jane */
            displayName: string;
        };
        TokenResponseDto: {
            accessToken: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example P@ssw0rd! */
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /** @description 프리미엄 구독 여부(임시) */
            isPremium: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Question: {
            /** Format: uuid */
            id: string;
            /** @example 술 잘 먹을 것 같은 친구 */
            text: string;
        };
        Profile: {
            /** Format: uuid */
            id: string;
            /** @example 하리니 */
            displayName: string;
            /** @example https://i.pravatar.cc/600?img=5 */
            photoUrl: string | null;
            /**
             * @description 나와의 거리(km, 목업)
             * @example 17
             */
            distanceKm: number | null;
            /** @example @hx_rxx_ 맞팔도 받아용! */
            bio: string | null;
            /**
             * @example [
             *       "홍대",
             *       "스티커 사진",
             *       "닌텐도"
             *     ]
             */
            interests: string[];
        };
        ChoiceFeed: {
            question: components["schemas"]["Question"];
            /** @description 랜덤하게 주어지는 후보 카드 */
            candidates: components["schemas"]["Profile"][];
        };
        SelectChoiceDto: {
            /**
             * Format: uuid
             * @description 제시된 질문 ID
             */
            questionId: string;
            /**
             * Format: uuid
             * @description 선택한 유저 ID
             */
            selectedUserId: string;
        };
        Viewer: {
            /** Format: uuid */
            id: string;
            /** @example 나 */
            displayName: string;
            /** @example https://i.pravatar.cc/600?img=8 */
            photoUrl: string | null;
            /** @description 프리미엄 구독 여부(임시) */
            isPremium: boolean;
        };
        Top3Item: {
            /** @example 술 잘 먹을 것 같은 친구 */
            questionText: string;
            /**
             * @description 그 주제로 받은 픽 수
             * @example 12
             */
            votes: number;
        };
        ReceivedPick: {
            /** @description 나를 픽한 사람 (비프리미엄이면 photoUrl=null) */
            selector: components["schemas"]["Profile"];
            /**
             * Format: uuid
             * @description 나를 픽한 주제의 질문 ID
             */
            questionId: string;
            /**
             * @description 나를 픽한 주제(대표: 가장 최근 픽)
             * @example 1프로라도 관심이 가는 친구
             */
            questionText: string;
            /** Format: date-time */
            pickedAt: string;
            /** @description 그 사람이 받은 픽 Top3 */
            top3: components["schemas"]["Top3Item"][];
        };
        ReceivedPicks: {
            /**
             * @description 내가 받은 총 픽 수
             * @example 174
             */
            total: number;
            items: components["schemas"]["ReceivedPick"][];
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            senderId: string;
            /** @example 안녕하세요! 픽 감사해요 ㅎㅎ */
            text: string;
            /**
             * Format: date-time
             * @description 읽은 시각 (null이면 안읽음)
             */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ConversationSummary: {
            /** Format: uuid */
            id: string;
            /** @description 상대 */
            partner: components["schemas"]["Profile"];
            /** @description 소통 시작의 픽 주제(뱃지용) */
            questionText: string | null;
            /** @description 마지막 메시지 (없으면 null) */
            lastMessage: components["schemas"]["Message"] | null;
            /**
             * @description 안읽은 메시지 수
             * @example 2
             */
            unreadCount: number;
        };
        CreateConversationDto: {
            /**
             * Format: uuid
             * @description 소통할 상대 유저 ID
             */
            targetUserId: string;
            /**
             * Format: uuid
             * @description 소통 시작의 픽 주제(뱃지용)
             */
            questionId?: string;
        };
        SendMessageDto: {
            /** @example 안녕하세요! */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    ChoiceController_getFeed: {
        parameters: {
            query?: {
                questionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoiceFeed"];
                };
            };
        };
    };
    ChoiceController_select: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectChoiceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoiceFeed"];
                };
            };
        };
    };
    ViewerController_getViewer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Viewer"];
                };
            };
        };
    };
    ViewerController_subscribePremium: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Viewer"];
                };
            };
        };
    };
    ReceivedPicksController_getReceivedPicks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedPicks"];
                };
            };
        };
    };
    ConversationsController_getConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
        };
    };
    ConversationsController_createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
        };
    };
    ConversationsController_getMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
        };
    };
    ConversationsController_sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
}
