/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 전화번호로 인증번호(OTP) 발급 + 문자 발송 (SMS 미설정 시 목 모드 — devCode로 응답) */
        post: operations["AuthController_requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 인증번호 검증 — 기존 유저면 토큰, 신규면 가입 진행 신호 */
        post: operations["AuthController_verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 인증 완료 후 회원가입 (생일·닉네임·성별·약관 동의) */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 액세스 토큰 재발급 (리프레시 토큰 회전) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 — 건네받은 리프레시 토큰만 폐기(멱등) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 인증된 유저 조회 */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 초이스 피드 (질문 + 랜덤 후보 4명)
         * @description questionId 없으면 새 질문(초기/스킵), 있으면 같은 질문 + 새 후보(다시 섞기).
         */
        get: operations["ChoiceController_getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/choices/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카드 선택 기록 후 다음 피드 반환
         * @description 로그인한 "나"를 selector로 기록 → 받은픽 데이터의 출처.
         */
        post: operations["ChoiceController_select"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/viewer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 유저("나") 조회 (프리미엄 여부 포함) */
        get: operations["ViewerController_getViewer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/viewer/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 프로필 수정 (사진·자기소개·관심사) — 보낸 필드만 반영 */
        patch: operations["ViewerController_updateProfile"];
        trace?: never;
    };
    "/viewer/premium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 프리미엄 구독('가입하기') — 즉시 프리미엄 ON(임시) */
        post: operations["ViewerController_subscribePremium"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/received-picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 나를 픽한 사람 목록 + 각자의 받은픽 Top3
         * @description 비프리미엄이면 selector 사진은 서버에서 가려진다(photoUrl=null).
         */
        get: operations["ReceivedPicksController_getReceivedPicks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 소통 목록(메시지함) */
        get: operations["ConversationsController_getConversations"];
        put?: never;
        /** 소통하기 — 대화 생성(이미 있으면 반환) */
        post: operations["ConversationsController_createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 메시지 히스토리 (열면 읽음 처리) */
        get: operations["ConversationsController_getMessages"];
        put?: never;
        /** 메시지 전송 (REST 폴백; 정식 송신은 소켓) */
        post: operations["ConversationsController_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 프로필 사진 업로드 (multipart/form-data, 필드명 file) */
        post: operations["UploadsController_uploadPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness check (app + DB) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequestOtpDto: {
            /**
             * @description 전화번호(하이픈 허용)
             * @example 010-1234-5678
             */
            phone: string;
        };
        RequestOtpResponseDto: {
            /**
             * @description 개발 환경에서만 채워지는 인증번호(목 OTP). 운영에선 null.
             * @example 123456
             */
            devCode: string | null;
        };
        VerifyOtpDto: {
            /**
             * @description 전화번호(하이픈 허용)
             * @example 010-1234-5678
             */
            phone: string;
            /**
             * @description 6자리 인증번호
             * @example 123456
             */
            code: string;
        };
        VerifyOtpResponseDto: {
            /** @description 기존 유저면 발급된 토큰, 신규 유저면 null(가입 진행 필요). */
            accessToken: string | null;
            /** @description 기존 유저면 리프레시 토큰, 신규 유저면 null. */
            refreshToken: string | null;
            /** @description 가입 이력이 없는 신규 유저인지 여부. */
            isNewUser: boolean;
        };
        /** @enum {string} */
        Gender: "MALE" | "FEMALE" | "OTHER";
        SignupDto: {
            /**
             * @description 전화번호(하이픈 허용)
             * @example 010-1234-5678
             */
            phone: string;
            /**
             * Format: date
             * @description 생년월일 (ISO 날짜)
             * @example 2000-09-20
             */
            birthday: string;
            /** @example 아니근데옥지얌 */
            nickname: string;
            /** @example FEMALE */
            gender: components["schemas"]["Gender"];
            /**
             * @description 이용약관 동의 (필수 — true가 아니면 가입 불가)
             * @example true
             */
            agreeTerms: boolean;
            /**
             * @description 개인정보처리방침 동의 (필수 — true가 아니면 가입 불가)
             * @example true
             */
            agreePrivacy: boolean;
            /**
             * @description 마케팅 정보 수신 동의 (선택)
             * @default false
             */
            agreeMarketing: boolean;
        };
        TokenResponseDto: {
            /** @description 짧게 사는 액세스 토큰(JWT). 기본 15분. */
            accessToken: string;
            /** @description 액세스 토큰 재발급용 리프레시 토큰. 재발급 시마다 새 값으로 회전한다. */
            refreshToken: string;
        };
        RefreshDto: {
            /**
             * @description 발급받은 리프레시 토큰 원문(64자 hex)
             * @example a3f9c1...
             */
            refreshToken: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /**
             * @description 전화번호(정규화된 숫자만)
             * @example 01012345678
             */
            phone: string;
            /**
             * Format: date
             * @description 생년월일
             */
            birthday: string | null;
            displayName: string;
            /** @description 성별 (가입 이전 데이터는 null일 수 있음) */
            gender: components["schemas"]["Gender"] | null;
            /** @description 프리미엄 구독 여부(임시) */
            isPremium: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Question: {
            /** Format: uuid */
            id: string;
            /** @example 술 잘 먹을 것 같은 친구 */
            text: string;
        };
        Profile: {
            /** Format: uuid */
            id: string;
            /** @example 하리니 */
            displayName: string;
            /** @example https://i.pravatar.cc/600?img=5 */
            photoUrl: string | null;
            /**
             * @description 나와의 거리(km, 목업)
             * @example 17
             */
            distanceKm: number | null;
            /** @example @hx_rxx_ 맞팔도 받아용! */
            bio: string | null;
            /**
             * @example [
             *       "홍대",
             *       "스티커 사진",
             *       "닌텐도"
             *     ]
             */
            interests: string[];
        };
        ChoiceFeed: {
            question: components["schemas"]["Question"];
            /** @description 랜덤하게 주어지는 후보 카드 */
            candidates: components["schemas"]["Profile"][];
        };
        SelectChoiceDto: {
            /**
             * Format: uuid
             * @description 제시된 질문 ID
             */
            questionId: string;
            /**
             * Format: uuid
             * @description 선택한 유저 ID
             */
            selectedUserId: string;
        };
        Viewer: {
            /** Format: uuid */
            id: string;
            /** @example 나 */
            displayName: string;
            /** @example https://i.pravatar.cc/600?img=8 */
            photoUrl: string | null;
            /** @description 프리미엄 구독 여부(임시) */
            isPremium: boolean;
            /**
             * @description 자기소개
             * @example 조용한 카페 좋아해요
             */
            bio: string | null;
            /**
             * @description 관심사 태그
             * @example [
             *       "영화",
             *       "러닝"
             *     ]
             */
            interests: string[] | null;
        };
        UpdateProfileDto: {
            /**
             * @description 업로드 API가 돌려준 사진 경로
             * @example /uploads/3f1a....jpg
             */
            photoUrl?: string | null;
            /**
             * @description 자기소개
             * @example 조용한 카페 좋아해요
             */
            bio?: string | null;
            /**
             * @description 관심사 태그 (최대 10개)
             * @example [
             *       "영화",
             *       "러닝",
             *       "카페"
             *     ]
             */
            interests?: string[];
        };
        Top3Item: {
            /** @example 술 잘 먹을 것 같은 친구 */
            questionText: string;
            /**
             * @description 그 주제로 받은 픽 수
             * @example 12
             */
            votes: number;
        };
        ReceivedPick: {
            /** @description 나를 픽한 사람 (비프리미엄이면 photoUrl=null) */
            selector: components["schemas"]["Profile"];
            /**
             * Format: uuid
             * @description 나를 픽한 주제의 질문 ID
             */
            questionId: string;
            /**
             * @description 나를 픽한 주제(대표: 가장 최근 픽)
             * @example 1프로라도 관심이 가는 친구
             */
            questionText: string;
            /** Format: date-time */
            pickedAt: string;
            /** @description 그 사람이 받은 픽 Top3 */
            top3: components["schemas"]["Top3Item"][];
        };
        ReceivedPicks: {
            /**
             * @description 내가 받은 총 픽 수
             * @example 174
             */
            total: number;
            items: components["schemas"]["ReceivedPick"][];
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            senderId: string;
            /** @example 안녕하세요! 픽 감사해요 ㅎㅎ */
            text: string;
            /**
             * Format: date-time
             * @description 읽은 시각 (null이면 안읽음)
             */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ConversationSummary: {
            /** Format: uuid */
            id: string;
            /** @description 상대 */
            partner: components["schemas"]["Profile"];
            /** @description 소통 시작의 픽 주제(뱃지용) */
            questionText: string | null;
            /** @description 마지막 메시지 (없으면 null) */
            lastMessage: components["schemas"]["Message"] | null;
            /**
             * @description 안읽은 메시지 수
             * @example 2
             */
            unreadCount: number;
        };
        CreateConversationDto: {
            /**
             * Format: uuid
             * @description 소통할 상대 유저 ID
             */
            targetUserId: string;
            /**
             * Format: uuid
             * @description 소통 시작의 픽 주제(뱃지용)
             */
            questionId?: string;
        };
        SendMessageDto: {
            /** @example 안녕하세요! */
            text: string;
        };
        UploadResult: {
            /**
             * @description API 서버 기준 상대 경로
             * @example /uploads/3f1a....jpg
             */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestOtpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOtpResponseDto"];
                };
            };
        };
    };
    AuthController_verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyOtpResponseDto"];
                };
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description 폐기 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    ChoiceController_getFeed: {
        parameters: {
            query?: {
                questionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoiceFeed"];
                };
            };
        };
    };
    ChoiceController_select: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectChoiceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChoiceFeed"];
                };
            };
        };
    };
    ViewerController_getViewer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Viewer"];
                };
            };
        };
    };
    ViewerController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Viewer"];
                };
            };
        };
    };
    ViewerController_subscribePremium: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Viewer"];
                };
            };
        };
    };
    ReceivedPicksController_getReceivedPicks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedPicks"];
                };
            };
        };
    };
    ConversationsController_getConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
        };
    };
    ConversationsController_createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
        };
    };
    ConversationsController_getMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
        };
    };
    ConversationsController_sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    UploadsController_uploadPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
}
